blueprint:
  name: tado hijack - Open Window
  description: Set Climate mode when window open/closes - v1.0.0
  domain: automation
  source_url: https://github.com/kimeikato/hass-blueprints/blob/main/tado/tado_open_window.yaml
  input:
    window:
      name: Window
      selector:
        entity:
          device_class: window
    climate:
      name: Climate
      selector:
        entity:
          domain: climate

mode: restart

trigger:
  - platform: state
    entity_id:
      - !input window
    to: "on"
  - platform: state
    entity_id:
      - !input window
    from: "on"

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input window
            state: "on"
        sequence:
          - action: tado_hijack.set_mode
            data:
              hvac_mode: "off"
              overlay: manual
              refresh_after: true
              entity_id: !input climate
      - conditions:
          - condition: state
            entity_id: !input window
            state: "off"
        sequence:
          - action: tado_hijack.set_mode
            data:
              hvac_mode: heat
              overlay: next_block
              refresh_after: true
              temperature: 10
              duration: 10
              entity_id: !input climate